Repository EjjumO-Gen/EjjumO-FE, pull requests merged in 2024-09, with the labels that each got.

#3 [chore] vite-plugin-svgr 설치
  package-lock.json
  package.json
  vite.config.js
Labels: chore

#4 [feat] 메인페이지 구현
  Icon 
  index.html
  package.json
  src/App.jsx
  src/assets/images/account.svg
  src/assets/images/arrow_forward_ios.png
  src/assets/images/image1.png
  src/assets/images/lock.svg
  src/assets/images/logo.svg
  src/assets/images/main_banner.png
  src/assets/images/make_playlist.svg
  src/assets/images/profile.svg
  src/assets/images/search.svg
  src/assets/images/thumb_up.svg
  src/components/ListItem.jsx
  src/components/ListSection.jsx
  src/components/layout/Header.jsx
  src/index.css
  src/pages/main/MainPage.jsx
  src/pages/playlist/ViewPlaylistPage.jsx
  src/styles/font.css
Labels: feat

#6 [feat] 플리 조회 페이지 구현
  package-lock.json
  package.json
  src/App.jsx
  src/assets/images/add.svg
  src/assets/images/border_color.svg
  src/assets/images/chat.svg
  src/assets/images/chat_bubble.svg
  src/assets/images/play_circle.svg
  src/assets/images/thumbs_FillOff.svg
  src/assets/images/thumbs_FillOn.svg
  src/components/ListItem.jsx
  src/components/ListSection.jsx
  src/components/PlaylistItem.jsx
  src/components/SongItem.jsx
  src/pages/main/MainPage.jsx
  src/pages/playlist/ViewPlaylistPage.jsx
Labels: feat

#13 feat: 댓글창 레이아웃 구현
  src/App.jsx
  src/assets/images/arrow_circle_up.svg
  src/assets/images/arrow_circle_up_green.svg
  src/assets/images/arrow_forward.svg
  src/assets/images/arrow_forward_ios.png
  src/components/CommentAdd.jsx
  src/components/CommentItem.jsx
  src/components/ListSection.jsx
  src/components/PlaylistItem.jsx
  src/pages/comment/CommentPage.jsx
  src/pages/main/MainPage.jsx
  src/pages/playlist/ViewPlaylistPage.jsx
Labels: feat

#15 [fix] 댓글창 디자인 수정
  src/components/CommentAdd.jsx
Labels: fix

#19 [feat] 플리 생성 페이지 레이아웃 구현
  src/App.jsx
  src/assets/images/createplaylist_logo.svg
  src/assets/images/delete_button.svg
  src/assets/images/search_button.svg
  src/components/CommentAdd.jsx
  src/pages/comment/CommentPage.jsx
  src/pages/main/MainPage.jsx
  src/pages/playlist/CreatePlaylistPage.jsx
  src/pages/playlist/ViewPlaylistPage.jsx
Labels: feat

#21 [feat] axios 세팅, 메인페이지 API 연동
  package-lock.json
  package.json
  src/apis/axios.setting.js
  src/apis/playlist.js
  src/apis/user.js
  src/components/ListSection.jsx
  src/pages/main/MainPage.jsx
Labels: feat

#24 [feat] 임시 머지
  src/apis/provider.js
  src/components/SearchSongItem.jsx
  src/index.css
  src/pages/playlist/CreatePlaylistPage.jsx
Labels: feat

#25 [feat] 플리 조회 API 연동
  src/apis/playlist.js
  src/apis/user.js
  src/pages/playlist/ViewPlaylistPage.jsx
Labels: feat

#27 [feat] 댓글 조회 API 연동
  package-lock.json
  package.json
  src/apis/comment.js
  src/apis/playlist.js
  src/components/CommentItem.jsx
  src/pages/comment/CommentPage.jsx
  src/pages/playlist/ViewPlaylistPage.jsx
Labels: feat

#31 [feat] 댓글 작성 API
  src/apis/comment.js
  src/components/CommentAdd.jsx
  src/pages/comment/CommentPage.jsx
Labels: feat

#34 [feat] 플리 생성
  src/apis/playlist.js
  src/pages/playlist/CreatePlaylistPage.jsx
  src/pages/playlist/ViewPlaylistPage.jsx
Labels: feat

#36 feat: 따봉 API 연동
  src/apis/playlist.js
  src/components/PlaylistItem.jsx
  src/pages/playlist/ViewPlaylistPage.jsx
Labels: FEAT

#37 [feat] 플리 삭제 api 연동
  src/App.jsx
  src/apis/playlist.js
  src/assets/images/edit_button.svg
  src/components/PlaylistItem.jsx
  src/pages/playlist/CreatePlaylistPage.jsx
  src/pages/playlist/EditPlaylistPage.jsx
Labels: FEAT

#39 [feat] 프로필 조회 api 연동
  src/apis/user.js
  src/components/ProfileItem.jsx
  src/components/UserItem.jsx
  src/pages/profile/ViewMyProfilePage.jsx
  src/pages/profile/ViewProfilePage.jsx
Labels: FEAT

#42 [feat] 유튜브 재생목록 생성
  package-lock.json
  package.json
  src/App.jsx
  src/apis/auth.js
  src/apis/provider.js
  src/components/PlaylistItem.jsx
  src/components/SearchSongItem.jsx
  src/pages/auth/AuthPage.jsx
  src/pages/playlist/CreatePlaylistPage.jsx
  src/pages/playlist/ViewPlaylistPage.jsx
  src/store/playlist.js
  src/utils/token.js
Labels: FEAT
